### ISSUE TITLE
The return value for Test-TargetResource is reversed

### ISSUE THREAD

**Issue by bk147** [PowerShell/xPowerShellExecutionPolicy#1]
In the Test-TargetResource the return value is reversed ($true for $false).
One way to correct this is to replace:

If($(Get-ExecutionPolicy) -eq $ExecutionPolicy)

with

If($(Get-ExecutionPolicy) -ne $ExecutionPolicy)

**Comment by KarolKaczmarek** [comment]
Hi @bk147 
Checked it out and looks good to me:
```
 If($(Get-ExecutionPolicy) -eq $ExecutionPolicy)
    {
        return $true
    }
    else
    {
        return $false
    }
```
If current execution policy (Get-ExecutionPolicy) equals what we expect it to be ($ExecutionPolicy), then we return $true (resource is in desired state). Otherwise - we return $false.

Seems fine, so closing this issue, but feel free to reopen if I'm not understanding your request correctly.
