### ISSUE TITLE
xPowerShellExecutionPolicy: Test-TargetResource never returns true

### ISSUE THREAD

**Issue by HansOMartinsen** [PowerShell/xPowerShellExecutionPolicy#8]
Because the Set-ExecutionPolicy without the use of the Policy parameter sets the LocalMachine scope, ant the Get-ExecutionPolicy will be overridden by anything in a more spesific scope, the Test-Resource wil almost always return false.

Tor remedy this a scope parameter should be added. with a default scope of LocalMachine

**Comment by larssb** [comment]
Ohhh man...this explains why I get a "Not complaint" node when its configuration is controlled by DSC. Tried via Azure Automation.

What is the status on this pull request #9 ?

It sounds like it will solve the issue. Would be more than wonderful. 

Thank you so much :-)

PS: If the pull request cannot be completed because Mr. @HansOMartinsen has been inactive for the last approximately nine months I could do a pull request on the same fix. I would be more than happy to help. 👍

**Comment by GerbenWelter** [comment]
I'm also willing to provide a PR but I'm wondering if the scope shouldn't always be LocalMachine and could be hardcoded?

**Comment by larssb** [comment]
@GerbenWelter nice work! I'm really waiting for this to work.

Thnx
